name: Pull request build check

# Trigger on push or pull request
on:
  push:
    branches:
      - story*
      - develop
      - release*
      - master
  pull_request:
    branches:
      - story*
      - develop
      - release*
      - master

jobs:
  pr_build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Build some version to check build-ability
      - name: Build dummy version
        run: ./gradlew clean assembleDummyApiDebug
