name: Pull request build check

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - story*
      - develop
      - release*
      - master
  pull_request:
    branches:
      - story*
      - develop
      - release*
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: ./gradlew clean assembleDummyApiDebug
