name: Build and deploy stageApi QA version

# Trigger on push
on:
  push:
    branches:
      - task/CTAA-1329_set_up_CI_pipelines # just for testing
    tags:
      - QA*

jobs:
  build_and_archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare secrets
        env:
          DEBUG_KEYSTORE_FILE_BASE64: ${{ secrets.DEBUG_KEYSTORE_FILE_BASE64 }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
          GOOGLE_SERVICES_PROD: ${{ secrets.GOOGLE_SERVICES_PROD }}
          GOOGLE_SERVICES_STAGE: ${{ secrets.GOOGLE_SERVICES_STAGE }}
        run: |
          mkdir keystore
          mkdir ./app/src/prodApi
          mkdir ./app/src/stageApi
          echo "$DEBUG_KEYSTORE_FILE_BASE64" | base64 -d > keystore/android_debug.keystore
          echo "$LOCAL_PROPERTIES" > ./local.properties
          echo "$GOOGLE_SERVICES_PROD" > ./app/src/prodApi/google-services.json
          echo "$GOOGLE_SERVICES_STAGE" > ./app/src/stageApi/google-services.json
      - name: Build QA version
        run: ./gradlew clean assembleStageApiBeta
      - name: Archive to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: QA_build
          path: app/build/outputs
    # TODO upload to appCenter